<a href="https://colab.research.google.com/github/yukai920722/2022-ksu-11002/blob/main/4100e104.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.4.2
bs4                           0.0.1
CacheC

In [ ]:
lmport numpy as np
x=np.arange(2,10)
x[0]

SyntaxError: ignored

In [ ]:
numpy.linspace(start,stop,num=50,==>endpoint=True,retstep=False,dtype=None,axis=0)

SyntaxError: ignored

In [ ]:
!hostnamc

/bin/bash: hostnamc: command not found


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
import numpy as np

b = np.linspace(0, 2, 4)
b

# array([0.        , 0.66666667, 1.33333333, 2.        ])

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
c = np.linspace(0, 2, 4, endpoint=False) 
c

# array([0. , 0.5, 1. , 1.5])

array([0. , 0.5, 1. , 1.5])

In [ ]:
import numpy as np

ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [ ]:
import numpy as np

ar1=np.array([2,4,6,8]); ar1.dtype

dtype('int64')

In [ ]:
ar2=np.array([2,-1,6,3], dtype='float');
ar2.dtype

dtype('float64')

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.ndim

2

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.shape

(2, 3)

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.size

6

In [ ]:
import numpy as np

ar1=np.array([2,4,6,8]); 
ar1.dtype

dtype('int64')

In [ ]:
ar2=np.array([2,-1,6,3], dtype='float'); 
ar2.dtype

dtype('float64')

In [ ]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [ ]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [ ]:
import numpy as np

ar3=np.array([2.,4,6,8]); 

ar3.dtype

dtype('float64')

In [ ]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  

In [ ]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.ndim


2

In [ ]:
import numpy as np
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr 
(1)array =?
(2)shape =?
(3)dimension =?
(4)dtype

In [ ]:
import numpy as np

ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr 
(1)array =?
(2)shape =?
(3)dimension =?
(4)dtype

SyntaxError: ignored

In [ ]:
np.tile(np.array([[1,2],[6,7]]),3)
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [ ]:
import numpy as np
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
np.tile(np.array([[1,2],[6,7]]),3)
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [ ]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
ar[2,-1]


13

In [ ]:
Import numpy as np
x = np.arange(2,10)
x[0]

SyntaxError: ignored

In [ ]:
ar=2*np.arange(6); 
ar[:3]=1;

In [ ]:
import numpy as np

# x = np.arange(2,10)
x = np.arange(2,10).reshape(2,4)
y = np.arange(2,10).reshape(4,2)
x
y
#x.shape

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar
ar.ravel()
ar.T
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [ ]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a + b

array([3., 4., 5.])

In [ ]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
ar[2,:]

array([11, 12, 13])

In [ ]:
rand(d0, d1, …, dn)	Random values in a given shape.
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).
random([size])	Return random floats in the half-open interval [0.0, 1.0).
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).
sample([size])	Return random floats in the half-open interval [0.0, 1.0).
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array
bytes(length)	Return random bytes.

SyntaxError: ignored

In [ ]:
np.tile(np.array([[1,2],[6,7]]),3)
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

arr+arr
arr-arr
arr*arr
1/arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
import numpy as np
z1 = np.zeros((2, 3))
z2 = np.ones((2, 3))
z1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
arr = np.arange(10)
arr

np.sqrt(arr)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
ar=np.array([[1,1],[1,1]]);
ar2=np.array([[2,2],[2,2]]);

# 標準Array multiplication(矩陣相乘) 
ar*ar2

# 內積運算
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [ ]:
import numpy as np

ar9b = np.eye(3);
ar9b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np

ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [ ]:
import numpy as np

ar12 = np.linspace(1., 4., 6) # start, end, num
ar12

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
import numpy as np

ar11=np.arange(2, 3, 0.1) # start, end, step
ar11

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 175.72 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.59 µs per loop


In [ ]:
ar=range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 5: 407 µs per loop


In [ ]:
import numpy as np

ar9a = np.array([[ 1.,  0.,  0.],[ 0.,  1.,  0.],[ 0.,  0.,  1.]]);
ar9a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import pandas as pd

In [ ]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]


c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2 > 0]


d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2


d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
'b' in obj2


True

In [ ]:
'e' in obj2


False

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isnull(obj4)


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj = pd.Series([41, 27, -25, 13,21])
obj

0    41
1    27
2   -25
3    13
4    21
dtype: int64

In [ ]:
obj.values

array([ 41,  27, -25,  13,  21])

In [ ]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.values

array([ 4,  7, -5,  3])

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [ ]:
obj2['a']

-5

In [ ]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [ ]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah': 5000}

obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'

obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

ValueError: ignored

In [ ]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

ValueError: ignored

In [ ]:
!wget https://raw.githubusercontent.com/PacktPublishing/Learning-Pandas-Second-Edition/master/data/msft.csv

--2022-03-16 02:37:58--  https://raw.githubusercontent.com/PacktPublishing/Learning-Pandas-Second-Edition/master/data/msft.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 153109 (150K) [text/plain]
Saving to: ‘msft.csv’

msft.csv            100%[===================>] 149.52K  --.-KB/s    in 0.04s   

2022-03-16 02:37:59 (4.02 MB/s) - ‘msft.csv’ saved [153109/153109]



In [ ]:
!head -n 5 msft.csv 

Date,Open,High,Low,Close,Volume
7/21/2014,83.46,83.53,81.81,81.93,2359300
7/18/2014,83.3,83.4,82.52,83.35,4020800
7/17/2014,84.35,84.63,83.33,83.63,1974000
7/16/2014,83.77,84.91,83.66,84.91,1755600


In [ ]:
msft = pd.read_csv("./msft.csv")
msft[:5]

Date   Open   High    Low  Close   Volume
0  7/21/2014  83.46  83.53  81.81  81.93  2359300
1  7/18/2014  83.30  83.40  82.52  83.35  4020800
2  7/17/2014  84.35  84.63  83.33  83.63  1974000
3  7/16/2014  83.77  84.91  83.66  84.91  1755600
4  7/15/2014  84.30  84.38  83.20  83.58  1874700

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

ValueError: ignored

In [ ]:
obj

0    41
1    27
2   -25
3    13
4    21
dtype: int64

In [ ]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [ ]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2


year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [ ]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [ ]:
del frame2['eastern']
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
pd.DataFrame(pop, index=[2001, 2002, 2003])


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)


Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
frame2.values


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [ ]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]


Index(['b', 'c'], dtype='object')

In [ ]:
index[1] = 'd'


TypeError: ignored

In [ ]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3


state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.values


array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])